### ISSUE TITLE
Feature Request: Could you add a way to add it into downloader.ini so the script will update with Update All?

### ISSUE THREAD

**Issue by Jlmbles** [Koston-0xDEADBEEF/MiSTer-ROMweasel#3]
Not sure if this can already be done, since I am new with Mister. But I noticed that  downloader.ini requires a json to download the latest version.

**Comment by Koston-0xDEADBEEF** [comment]
This only makes sense, if romweasel support was officially added to `update_all` upstream. So, ask them instead - I'm willing to do the implementation in case it's accepted.

Without official support, better way to automate updates would be adding a self-update feature into it. I did consider it, but since romweasel isn't actively developed it didn't seem like worth the effort.

**Comment by Koston-0xDEADBEEF** [comment]
Note, support for automatic updating via `downloader.ini` was added in commit dd2e8995f9804ef30aeb0d297aca9c64d95fc28a
